# Generated by Django 2.1 on 2018-12-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': (('change_own_recipe', 'Can change own recipe'),)},
        ),
    ]
